version: 2
updates:
  - package-ecosystem: "github-actions"
    commit-message:
      prefix: "chore"
      include: "scope"
    directory: "/"
    schedule:
      interval: "daily"

  - package-ecosystem: "npm"
    commit-message:
      prefix: "chore"
      include: "scope"
    directory: "/"
    ignore:
      - dependency-name: "@types/node"
        update-types: ['version-update:semver-major']
    schedule:
      interval: "daily"
    versioning-strategy: "increase"
