#!/usr/bin/env bash

set -euo pipefail

git config --global user.email "1182361+ianwremmel@users.noreply.github.com"
git config --global user.name "Automation"

export TARGET_BRANCH=main
export TOKEN=$CHECK_RUN_REPORTER__INTEGRATIONS_PUBLISH_TOKEN

DESTINATION_REPOSITORY_USERNAME=check-run-reporter \
  DESTINATION_REPOSITORY_NAME=check-run-reporter-buildkite-plugin \
  SOURCE_DIRECTORY=integrations/check-run-reporter-buildkite-plugin \
  ./scripts/publish-to-repo

DESTINATION_REPOSITORY_USERNAME=check-run-reporter \
  DESTINATION_REPOSITORY_NAME=action \
  SOURCE_DIRECTORY=integrations/action \
  ./scripts/publish-to-repo
