extends:
  - 'plugin:@ianwremmel/ianwremmel/node'
  - prettier

overrides:
  # make sure eslint lints all files
  - files:
      - '**/*.ts'
    extends:
      - 'plugin:@ianwremmel/ianwremmel/typescript'

  - files:
      - '**/*.js'
    parserOptions:
      sourceType: script

rules:
  no-console: error
