name: Check Run Reporter
description: Stop digging through logs and view test results without leaving GitHub.
author: https://github.com/check-run-reporter
requirements: []
configuration:
  properties:
    hostname:
      type: string
    report:
      type: string
    tests:
      type: string
    label:
      type: string
    root:
      type: string
    token:
      type: string
    url:
      type: string
  additionalProperties: false
  required:
    - report
    - token
