#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

# Lint staged files
npx --no-install lint-staged

# Make sure the readme TOC is up to date
if ! git diff --exit-code README.md; then
  echo 'README.md has unstaged changes. Please stage or stash them before committing'
  exit 1
fi
npm run build:readme
git add README.md