on: push
name: Validate
jobs:
  # TODO fix the fixup action to handle branch names other than master
  # fixup:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2.3.4
  #       with:
  #         fetch-depth: 0
  #     - uses: ianwremmel/prevent-fixup-commits@v1.0.2
  
  # TODO fix the nopush action to handle branch names other than master
  # nopush:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2.3.4
  #       with:
  #         fetch-depth: 0
  #     - uses: ianwremmel/prevent-nopush-commits@v1.0.3

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/cache@v2.1.4
        env:
          cache-name: cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - run: npm ci
      - run: npm run lint
        env:
          ESLINT_FORMAT_OPTIONS: '--format json-with-metadata --output-file reports/style/eslint.json'
          TSC_OPTIONS: '| tee reports/style/tsc.log'
      # There's a bug prevent CRR from working for this repo for the moment. 
      # Need to fix before CRR can be used here.
      # - uses: check-run-reporter/action@v2.0.0
      #   if: ${{ always() }}
      #   with:
      #     token: '62fe22eb-69e1-436d-b85a-82b14847e4cc'
      #     label: ESLint
      #     report: 'reports/style/eslint.json'
      # There's a bug prevent CRR from working for this repo for the moment. 
      # Need to fix before CRR can be used here.
      # - uses: check-run-reporter/action@v2.0.0
      #   if: ${{ always() }}
      #   with:
      #     token: '62fe22eb-69e1-436d-b85a-82b14847e4cc'
      #     label: TSC
      #     report: 'reports/style/tsc.log'

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2.1.4
        env:
          cache-name: cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - run: npm ci
      - run: npm test
      # There's a bug prevent CRR from working for this repo for the moment. 
      # Need to fix before CRR can be used here.
      # - uses: check-run-reporter/action@v2.0.0
      #   if: ${{ always() }}
      #   with:
      #     token: '62fe22eb-69e1-436d-b85a-82b14847e4cc'
      #     label: Unit Tests
      #     report: 'reports/junit/**/*.xml'